### ISSUE TITLE
some general comments

### ISSUE THREAD

**Issue by fatmai** [choldgraf/paper-pearc_2017#13]
- [ ] The title of section 2.2 is a little misleading b/c you are actually comparing the cloud approach to bootcamp approach. However, traditional teaching implies something else I think.
- [ ] In Section 4.2.1, when you describe what selections should be made. A figure with screenshots would be useful.
- [ ] I think the Methods section needs a different structure. The goal of that section is to give the reader the possibility to start off a new course based on this approach. However, this section does not allow an understanding + hands-on description of what one needs to do. 
- [ ] How about a section about retrospection on user's experience? Did you talk to people during/after the workshop, what did they report? What was the instructor's perspective? The main text touches on these topics but direct a experience report could be interesting and useful. Let me know if you would like to add that, I can help on that.

**Comment by arokem** [comment]
I seem to remember a post-workshop survey. Did any of the participants fill that out? 

I believe @dani-lbnl has access to this.

**Comment by choldgraf** [comment]
https://docs.google.com/forms/d/1T7n7Aj2CPfpEe7Pa6ny9Zb9aV4__y_DY9Vsrx9JJTb4/edit#responses

**Comment by choldgraf** [comment]
Those are answers to the questionnaire that we sent out.

Is anybody else taking a pass at this today? Maybe @aculich was planning to?

**Comment by aculich** [comment]
@choldgraf I have been waiting for comments/pull-requests to finish rolling in. I'll let you and @arokem merge how you like, then ping me and I will take a look at the latest draft.

**Comment by choldgraf** [comment]
OK - I'll look through / merge @fatmai's comments now then

**Comment by choldgraf** [comment]
ok all comments are merged - take a shot @aculich 

Quick thought:

I think we should have a step-by-step section showing the steps to take to set things up. As in, we should literally have something like "for instructors interested in hosting a similar event at their institution, the following steps should be taken:" and have a numbered list afterward, maybe with references to other sections or parts of the methods where we go into more detail.

**Comment by choldgraf** [comment]
Closing this in lieu of the larger issue with to-dos on it
