### ISSUE TITLE
Page count?

### ISSUE THREAD

**Issue by arokem** [choldgraf/paper-pearc_2017#17]
Anyone know how many pages are allowed for this conference submission? We're currently at 6 pages for the rendered PDF.

**Comment by aculich** [comment]
https://easychair.org/cfp/pearc17

> Submissions of both full papers and extended abstracts are permitted. Full papers of 5–8 pages are strongly preferred; extended abstracts should be at least 2 and no more than 4 pages. Authors with papers or extended abstracts accepted in the paper tracks must have at least one author attend the conference to make a 30­minute presentation.

**Comment by choldgraf** [comment]
So that's pretty much perfect then, yeah?

**Comment by choldgraf** [comment]
assuming we'll gain another 1/2 page for figures

**Comment by arokem** [comment]
looks like we're doing a "full paper" :-)

**Comment by choldgraf** [comment]
![](https://media.giphy.com/media/l0Ex39XVJoz6Wfh6w/giphy.gif)
