### ISSUE TITLE
Version 2.0 issues to be tackled

### ISSUE THREAD

**Issue by choldgraf** [choldgraf/paper-pearc_2017#19]
This is a place to keep track of what needs to be done before we're ready to submit.

🚢  it confirmation from:

- [x] @arokem 
- [x] @choldgraf
- [x] @aculich 
- [x] @fatmai 

Small things
---
- [x] Fix any inline refs and comments within the text.
- [ ] Make sure we reference any open-source software that was used in the class.
- [x] Come up with an easy-to-remember name for this model of teaching. What about something like **cluster-based bootcamps**?
  - [x] let's call these **container-based bootcamps**
- [x] Insert a table that gives an idea for how cost per student breaks down by size of the class / time.
- [x] Confirm / edit the short section at the end to succinctly list new developments that
  are needed. 
- [ ] Add some more citations where we make factual statements.
  - [x] added clark-proc-scipy-2014 to **Challenges of a traditional bootcamp approach**
- [x] We should include a link to our repositories as well as to the Docker setup images
  etc in the main text
- [x] Section 2.2: title little misleading b/c you are actually comparing the cloud approach to bootcamp approach. However, traditional teaching implies something else I think. (**has this already been addressed?**)
- [x] address XXX WHY IS JETSTREAM MORE ATTRACTIVE? HOW IS IT DIFF FROM TRADITIONAL HPC
- [ ] review Aaron's changes to section on **Cost and payment opportunities**

Medium things
---
- [x] Brain-storm the title for something a little bit more specific.
  - [x] updated paper with this proposed based on brainstorm: ~~**"Portable learning environments using container- and cloud-based technology for hands-on computational instruction"**~~
  - [x] title too long in paper heading, so split into title/subtitle **\title{Portable learning environments for hands-on computational instruction}\subtitle{Using container- and cloud-based technology to teach data science}**
 
- [x] Finalize title
- [x] In Section 4.2.1: Include a figure w/ screenshots
- [x] Methods section needs to be more "hands on" and step-by-step for people to get things working, in addition to describing the hardware / software that we used. (**I already addressed this along with @aculich but somebody should confirm / suggest changes**) 
- [x] Add a section about a user retrospective, or incorporate some of the quotes from the questionnaire.

**Comment by choldgraf** [comment]
@aculich or @arokem do you wanna take a pass? Maybe @fatmai could incorporate some kind of user retrospective?

**Comment by arokem** [comment]
- [ ] Brain-storm the title for something a little bit more specific.

**Comment by arokem** [comment]
## Potential titles 

"Container- and cloud-based learning environment for hands-on computational instruction"

"Using Docker and the Jetstream cloud for hands-on instruction of computational skills"

"Portable learning environments for ad-hoc computational workshops based on Docker and the Jetstream cloud"

**Comment by choldgraf** [comment]
(I'm thumbs-upping after I append above)

I like #1 above - we could also incorporate whatever "short name" we come up with to describe these kinds of things?

**Comment by aculich** [comment]
I also like title 1, though would like to also bring in the word "portable" from 3 since it captures the "mobility of compute" we talk about in Research IT... so how about some variation on 1 like this: "Portable learning environments using container- and cloud-based technology for hands-on computational instruction"

**Comment by aculich** [comment]
Regarding the term **cluster-based bootcamps**, since we technically didn't use a cluster, I've been expunging that word from earlier editions of the paper (though I see the latest edition it has reappeared :), replacing it with "cloud platform"... to the cyberinfrastructure community, the word cluster is going to imply an HPC cluster, but Jetstream has a very different architecture since it is cloud/VM based... so maybe we call it **container-based bootcamps** since that gives it the portability to any environment whether cloud, laptop... or even cluster (e.g. converting a Docker container to a Singularity container would let the software stack run on some HPC clusters).

**Comment by aculich** [comment]
@choldgraf  "Section 2.2: title ... has this already been addressed?" Yes, when I saw @fatmai 's comment I updated the section, so hopefully it addressed what she was pointing to... I thought I had checked it off on the checklist of #13, but maybe that didn't get saved?

**Comment by fatmai** [comment]
sorry folks I can only work on it after 7:45pm.

**Comment by choldgraf** [comment]
For a title, why not just "Portable learning environments using container- and cloud-based technology"

For the text, I took a quick look tonight and will make another quick look early tomorrow AM. We can do a short iteration on it then and then send it off!

**Comment by fatmai** [comment]
PR #24 includes one and the only user comment that I was able to use in terms of cloud-computing usage. Feel free to change framing if you like so. Looks good otherwise.

**Comment by choldgraf** [comment]
Hey all - I just pushed a new version that includes all the incorporated changes from you all, and also adds an image showing a sample jupyter notebook that the students see after going to an IP address (I just chose a random IP address and opened a notebook locally for the screenshot).

See a PDF of the generated result here:

https://www.dropbox.com/s/l4dkwzlogyrqsab/paper.pdf?dl=0

@arokem @aculich @fatmai where do we stand now? Anything else to do before submitting? If not, should we submit?!?!?

**Comment by arokem** [comment]
Looks great. 

🚢  it!

**Comment by choldgraf** [comment]
@aculich @fatmai see top-level comment in this thread to give "ship it" directive :)

**Comment by fatmai** [comment]
:ship: it!!

**Comment by choldgraf** [comment]
OK! It is shipped!!!!

![](http://cultofthepartyparrot.com/parrots/shipitparrot.gif)![](http://cultofthepartyparrot.com/parrots/shipitparrot.gif)![](http://cultofthepartyparrot.com/parrots/shipitparrot.gif)![](http://cultofthepartyparrot.com/parrots/shipitparrot.gif)![](http://cultofthepartyparrot.com/parrots/shipitparrot.gif)![](http://cultofthepartyparrot.com/parrots/shipitparrot.gif)

**Comment by aculich** [comment]
I had help reviewing the final draft...

![img_20170313_171232](https://cloud.githubusercontent.com/assets/118965/23881335/29746f68-0817-11e7-989c-708bbe58e850.jpg)
