### ISSUE TITLE
out of space for running latex

### ISSUE THREAD

**Issue by aculich** [choldgraf/paper-pearc_2017#4]
@choldgraf I noticed your comment in the [first draft](https://github.com/choldgraf/paper-pearc_2017/blob/master/paper.md) that "NOTE: I realized that I uninstalled latex on my mac because I ran out of space, so writing as markdown here, somebody else convert to latex" which might be due to docker containers taking up lots of space on your machine.

For example on my machine:
```
$ ls -lah ~/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
-rw-r--r-- 1 work staff 30G Mar  2 08:15 /Users/work/Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
```

Because we're using docker in a very ephemeral way you can just delete that big file, and then Docker will re-create it as a tiny file that will grow when you next try to run a docker image (which it will download again):

```
rm -f Library/Containers/com.docker.docker/Data/com.docker.driver.amd64-linux/Docker.qcow2
```

**Comment by aculich** [comment]
ps. I'll generate a latex version of the doc (the docker image we have been using actually contains latex as part of the Jupyter install).

**Comment by choldgraf** [comment]
the latex space problem was actually from a while ago, I can reinstall mactex and work from there, but I just didn't have the time to do it before writing the first draft. Feel free to convert to tex!

**Comment by choldgraf** [comment]
@aculich I just noticed that you said the docker image contains latex, shit that's a good idea, I didn't think about that. IIRC, latex is way smaller on linux. I wonder if there is a docker image out there that is *just* a barebones latex distribution on linux? I'm a little worried about running out of space if I grab one of the big scientific computing images

**Comment by aculich** [comment]
@choldgraf I updated the Makefile for the paper so that now, if you have docker installed on your Mac, you can run `make docker` in the paper directory and it will use the `jupyter/datascience-notebook` that we used for the course (which already has latex in it), to run a temporary docker container which invokes `make` inside the container. I also added the *.cls and *.bst files to the repo that I mentioned to @arokem were missing... so now we have a self-contained, self-building paper... if only it were self-writing. ;)

**Comment by choldgraf** [comment]
that's so cool - ok maybe I need to re-install a docker image for this...I deleted all of 'em before because of the space issues.
